development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:2ffb9dcc1a22cf594bc2157bd0d42612@pike.redistogo.com:9800/
  # channel_prefix: slack_production

  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>